//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agendae.basea
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class correo: IValidatableObject
    {

        
        private agendafEntiti db = new agendafEntiti();


        public int id_correo { get; set; }
        [Required]
        public string correo1 { get; set; }
        [Required]
        public Nullable<int> id_persona { get; set; }
    
        public virtual persona persona { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            var errores = new List<ValidationResult>();
            var hola = db.persona.Find(id_persona);

            if (hola == null)

            {
                errores.Add(new ValidationResult("la persona no existe"));
            }
            else
            {
                if (hola.disponible == false)

                {
                    errores.Add(new ValidationResult("la persona no existe"));
                }

            }
            /*
            if (hola.disponible == false)

            {
                errores.Add(new ValidationResult("la persona no existe"));
            }


    */



            return errores;
        }
    }
}
