//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agendae.basea
{
    using System;
    using System.Collections.Generic;
    
    public partial class correo
    {
        public int id_correo { get; set; }
        public string correo1 { get; set; }
        public Nullable<int> id_persona { get; set; }
    }
}
